services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: learn-docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "4001:5432"

volumes:
  pg_data: